language: python
python:
  - "2.6"
  - "2.7"
env:
   - PDFSERVER_SETTINGS=../test_settings.py
   - PDFSERVER_SETTINGS=../test_settings_celery.py
install:
  - sudo pip install -r requirements.txt --use-mirrors
  - sudo pip install -r celery_requirements.txt --use-mirrors
before_script:
  - PDFSERVER_SETTINGS=../test_settings_celery.py celeryd &
script:
  - python setup.py test
