application: pdfserver
version: 3
runtime: python
api_version: 1

handlers:
- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py
  login: admin
- url: .*
  script: appengine.py
