# Django settings for pdfserver project. These settings need to be applied
#   on top of the settings generated by ``django-admin startproject myserver``.

# pdfserver serves static files in debug mode
DEBUG = True

# Pdfserver supports l10n
USE_I18N = True
USE_L10N = True

# Sessions are needed for referencing files. We want to lose the files once
# gone from the site.
SESSION_EXPIRE_AT_BROWSER_CLOSE = True;

# Upload parent directory. Uploads will go to UPLOAD_TO/uploads
import os
UPLOAD_TO = os.path.abspath(os.path.join(DIRNAME, 'media'))

# If you don't have other applications installed, you can set this
ROOT_URLCONF = 'pdfserver.urls'

# pdfserver needs Sessions (installed by default) and supports Locales
MIDDLEWARE_CLASSES = (
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
)

# pdfserver needs the Sessions application
INSTALLED_APPS = (
    'django.contrib.sessions',
    'pdfserver',
)
